# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1ed25203acfcda9bb7d8f4f0e2e1f49764da0adc16067ed007dc8cbf07d710d63191cfbe212eafe5d1cf4165dc8b8dd61861db6586b3e9cf194997f9fde2285

test:
  secret_key_base: 03700cc971ad893d7a5803b5088e7d674ffc1767eb50e6e1d998bdcf386abdb4ab4393b6d864abc5cc8f3d27facee3c0580dc6834f6f6be0587571bb8b29aae2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
